name:                hs2lazy
version:             0.1.0.0
github:              "helvm/hs2lazy"
author:              "Kamil Adam"
maintainer:          "example@example.com"

extra-source-files:
- docs/README.md
- docs/CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs2lazy#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- parsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-binds
- -fno-warn-unused-matches


library:
  source-dirs: hs/src

executables:
  hs2lazy-exe:
    main:                Main.hs
    source-dirs:         hs/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs2lazy

tests:
  hs2lazy-test:
    main:                Spec.hs
    source-dirs:         hs/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs2lazy
    - tasty
    - tasty-hunit
    - tasty-hspec
    - tasty-golden
    - hspec
    - bytestring
    - filepath
    build-tools:
    - tasty-discover
